  import type { Book } from "./types";
  
  const books: Book[] = [
    {
      id_user : 1,
      id_book : 1,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 2,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 3,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 4,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 5,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 6,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 7,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 8,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 9,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 10,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 11,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 12,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
    {id_user : 1,
      id_book : 13,
      title: "Roma soy yo",
      author: "Santiago Posteguillo",
      type: "Tapa dura",
      price: 29.9,
      image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg",
      genre: "novela histórica"},
  ]

export {books};