  import type { Book } from "./types";


  const books: Book[] = [
  { 
    id_user: 1, 
    id_book: 1, 
    title: "Fundación", 
    author: "Isaac Asimov", 
    type: "Tapa Dura", 
    price: 25.99, 
    image: "https://www.baobablibros.es/imagenes_grandes/9788497/978849759924.GIF", 
    genre: "Ciencia Ficción",
    pages: "320",
    year: "1951",
    rating: 4.5,
    sinopsis: "Primera novela de la saga Fundación. En un futuro lejano, el matemático Hari Seldon prevé la caída del Imperio Galáctico y desarrolla la psicohistoria para minimizar el período de barbarie que seguirá, estableciendo una Fundación en los confines de la galaxia."
  },
  { 
    id_user: 1, 
    id_book: 2, 
    title: "Yo, Robot", 
    author: "Isaac Asimov", 
    type: "Tapa Blanda", 
    price: 22.99, 
    image: "https://m.media-amazon.com/images/I/71DquplUL-L._AC_UF894,1000_QL80_.jpg", 
    genre: "Ciencia Ficción",
    pages: "256",
    year: "1950",
    rating: 4.3,
    sinopsis: "Colección de relatos sobre robots positrónicos y las tres leyes de la robótica. Susan Calvin, robopsicóloga, narra la evolución de los robots desde simples máquinas hasta seres casi conscientes, explorando las implicaciones éticas y filosóficas de la inteligencia artificial."
  },
  { 
    id_user: 1, 
    id_book: 3, 
    title: "Los propios dioses", 
    author: "Isaac Asimov", 
    type: "Tapa Dura", 
    price: 24.99, 
    image: "https://m.media-amazon.com/images/I/71GGALG6zjL._AC_UF894,1000_QL80_.jpg", 
    genre: "Ciencia Ficción",
    pages: "288",
    year: "1972",
    rating: 4.2,
    sinopsis: "Ganadora del premio Hugo y Nebula. La humanidad descubre una fuente de energía ilimitada mediante el intercambio de materia con un universo paralelo, pero un científico descubre que este proceso puede destruir ambos universos."
  },
  { 
    id_user: 2, 
    id_book: 6, 
    title: "Reina Roja", 
    author: "Juan Gómez-Jurado", 
    type: "Tapa Dura", 
    price: 29.99, 
    image: "https://m.media-amazon.com/images/I/71GC9IBeQjL._AC_UF894,1000_QL80_.jpg", 
    genre: "Thriller",
    pages: "464",
    year: "2018",
    rating: 4.6,
    sinopsis: "Antonia Scott es especial. Muy especial. No es policía ni criminalista. Nunca ha empuñado un arma ni llevado una placa, y, sin embargo, ha resuelto decenas de crímenes. Pero hace un tiempo que Antonia no sale de su ático de Lavapiés."
  },
  { 
    id_user: 3, 
    id_book: 11, 
    title: "El Hobbit", 
    author: "J.R.R. Tolkien", 
    type: "Tapa Dura", 
    price: 24.99, 
    image: "https://m.media-amazon.com/images/I/81aYpbH9opS._AC_UF894,1000_QL80_.jpg", 
    genre: "Fantasía",
    pages: "368",
    year: "1937",
    rating: 4.7,
    sinopsis: "Bilbo Bolsón es un hobbit acomodado y sedentario hasta que el mago Gandalf y un grupo de enanos lo arrastran a una aventura para recuperar el tesoro custodiado por el dragón Smaug en la Montaña Solitaria. Un viaje que cambiará su vida para siempre."
  },
  { 
  id_user: 1, 
  id_book: 4, 
  title: "Las bóvedas de acero", 
  author: "Isaac Asimov", 
  type: "Tapa Blanda", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/71sEetDkeIL.jpg", 
  genre: "Ciencia Ficción",
  pages: "244",
  year: "1954",
  rating: 4.1,
  sinopsis: "Primera novela de la saga de robots protagonizada por Elijah Baley y R. Daneel. En un futuro donde los humanos viven en ciudades cubiertas y temen al aire libre, un detective debe resolver un asesinato con la ayuda de un robot humanoide, desafiando sus prejuicios."
},
{ 
  id_user: 1, 
  id_book: 5, 
  title: "El sol desnudo", 
  author: "Isaac Asimov", 
  type: "Tapa Dura", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/613SX2R1wJL.jpg", 
  genre: "Ciencia Ficción",
  pages: "272",
  year: "1957",
  rating: 4.0,
  sinopsis: "Segunda novela de Elijah Baley y R. Daneel. El detective terrestre viaja al planeta Aurora para resolver un asesinato en una sociedad donde los humanos evitan el contacto físico y viven aislados, dependiendo completamente de los robots."
},
{ 
  id_user: 2, 
  id_book: 7, 
  title: "Loba Negra", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Blanda", 
  price: 28.99, 
  image: "https://imagessl7.casadellibro.com/a/l/s5/97/9788466666497.webp", 
  genre: "Thriller",
  pages: "416",
  year: "2019",
  rating: 4.4,
  sinopsis: "Antonia Scott regresa en esta secuela de Reina Roja. Cuando la hija de la persona más rica de España es secuestrada, Antonia y Jon Gutiérrez deben enfrentarse a un enemigo que conoce todos sus secretos y debilidades."
},
{ 
  id_user: 2, 
  id_book: 8, 
  title: "Rey Blanco", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://imagessl5.casadellibro.com/a/l/s5/45/9788466668545.webp", 
  genre: "Thriller",
  pages: "448",
  year: "2020",
  rating: 4.5,
  sinopsis: "Tercera entrega de la trilogía. Antonia Scott se enfrenta a su mayor desafío cuando su mentor Mentor es secuestrado. Una carrera contrarreloj que la llevará a los límites de sus capacidades y pondrá a prueba todo lo que ha aprendido."
},
{ 
  id_user: 2, 
  id_book: 9, 
  title: "Cicatriz", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Blanda", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/718JlYPHi9L._AC_UF894,1000_QL80_.jpg", 
  genre: "Thriller",
  pages: "384",
  year: "2015",
  rating: 4.2,
  sinopsis: "Thriller independiente sobre Tom, un hombre corriente cuya vida cambia radicalmente cuando presencia un asesinato. Una historia sobre la supervivencia, la venganza y cómo las cicatrices del pasado pueden determinar nuestro futuro."
},
{ 
  id_user: 2, 
  id_book: 10, 
  title: "El Paciente", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/61E4a1a-HlL._AC_UF894,1000_QL80_.jpg", 
  genre: "Thriller",
  pages: "352",
  year: "2014",
  rating: 4.3,
  sinopsis: "Un psiquiatra recibe a un paciente que afirma ser Dios. Lo que comienza como una sesión rutinaria se convierte en un inquietante juego psicológico donde la realidad y la locura se entremezclan de forma perturbadora."
},
{ 
  id_user: 3, 
  id_book: 12, 
  title: "La Comunidad del Anillo", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://quelibroleo.com/images/libros/libro_1322009582.jpg", 
  genre: "Fantasía",
  pages: "576",
  year: "1954",
  rating: 4.8,
  sinopsis: "Primera parte de El Señor de los Anillos. Frodo Bolsón hereda un anillo mágico que resulta ser el Anillo Único del Señor Oscuro Sauron. Junto con la Comunidad del Anillo, emprende un peligroso viaje para destruirlo en Mount Doom."
},
{ 
  id_user: 3, 
  id_book: 13, 
  title: "Las Dos Torres", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/91sKjSJabqL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "544",
  year: "1954",
  rating: 4.7,
  sinopsis: "Segunda parte de la saga. La Comunidad se ha separado. Frodo y Sam continúan hacia Mordor con la traicionera ayuda de Gollum, mientras Aragorn, Legolas y Gimli persiguen a los orcos que capturaron a Merry y Pippin."
},
{ 
  id_user: 3, 
  id_book: 14, 
  title: "El Retorno del Rey", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91SI8FEoMuL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "624",
  year: "1955",
  rating: 4.9,
  sinopsis: "Conclusión épica de El Señor de los Anillos. Aragorn reclama su trono como Rey de Gondor, mientras Frodo y Sam enfrentan los peligros finales para destruir el Anillo en las llamas del Monte Doom y derrotar definitivamente a Sauron."
},
{ 
  id_user: 3, 
  id_book: 15, 
  title: "El Silmarillion", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91j7JtU5SjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "480",
  year: "1977",
  rating: 4.3,
  sinopsis: "La historia completa de la Tierra Media desde su creación. Relata la música de los Ainur, el despertar de los Elfos, las guerras contra Morgoth, la forja de los Silmarils y los eventos que preceden a El Hobbit y El Señor de los Anillos."
},
{ 
  id_user: 4, 
  id_book: 16, 
  title: "Un mago de Terramar", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://images.librotea.com/uploads/media/2024/02/29/historias-de-terramar-i.jpeg", 
  genre: "Fantasía",
  pages: "224",
  year: "1968",
  rating: 4.4,
  sinopsis: "Primera novela del Ciclo de Terramar. Ged, un joven mago impetuoso, libera accidentalmente una sombra maligna que lo persigue. Debe emprender un viaje de autodescubrimiento y madurez para enfrentar y comprender su propia oscuridad interior."
},
{ 
  id_user: 4, 
  id_book: 17, 
  title: "La mano izquierda de la oscuridad", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/320/original/portada_la-mano-izquierda-de-la-oscuridad_ursula-k-le-guin_202006041508.jpg", 
  genre: "Ciencia Ficción",
  pages: "304",
  year: "1969",
  rating: 4.2,
  sinopsis: "Obra maestra de la ciencia ficción. En el planeta Gethen, un enviado humano debe navegar entre la política y la cultura de una sociedad ambisexual. Una exploración profunda sobre género, política y la naturaleza humana."
},
{ 
  id_user: 4, 
  id_book: 18, 
  title: "Los desposeídos", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91awx73viIL.jpg", 
  genre: "Ciencia Ficción",
  pages: "384",
  year: "1974",
  rating: 4.5,
  sinopsis: "Shevek, un físico brillante del planeta anarquista Anarres, viaja al mundo capitalista Urras en busca de unificar las teorías físicas. Una poderosa reflexión sobre utopía, política, y la búsqueda del conocimiento científico."
},
{ 
  id_user: 4, 
  id_book: 19, 
  title: "Las tumbas de Atuan", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://m.media-amazon.com/images/I/81feP85w6sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "192",
  year: "1971",
  rating: 4.3,
  sinopsis: "Segunda novela de Terramar. Tenar, la suma sacerdotisa de las Tumbas de Atuan, encuentra su mundo trastornado cuando el mago Ged llega buscando la mitad perdida del Anillo de Erreth-Akbe. Una historia sobre liberación y autodeterminación."
},
{ 
  id_user: 4, 
  id_book: 20, 
  title: "La costa más lejana", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/81LOSKQX-sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "272",
  year: "1972",
  rating: 4.4,
  sinopsis: "Tercera novela de Terramar. El príncipe Arren acompaña a Ged en una misión para descubrir por qué la magia está desapareciendo del mundo. Un viaje hacia las tierras más lejanas donde enfrentarán la fuente de un mal ancestral."
},
  // data.ts - Actualización completa de libros 21-50
// filepath: c:\Users\jta_j\OneDrive\Documentos\Cursos\CodeNocht\03_Repositorios Git\modulo7\modulo7\retosEvaluables\reactAppBook\src\config\data.ts

// Reemplazar los libros 21-50 con los campos completos:

{ 
  id_user: 5, 
  id_book: 21, 
  title: "La llamada de Cthulhu", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/292/original/portada_la-llamada-de-cthulhu_h-p-lovecraft_201904111457.jpg", 
  genre: "Terror",
  pages: "192",
  year: "1928",
  rating: 4.4,
  sinopsis: "Relato icónico del horror cósmico. Un investigador descubre cultos secretos que adoran a Cthulhu, una entidad cósmica ancestral que yace dormida en la ciudad sumergida de R'lyeh, esperando despertar para dominar la humanidad."
},
{ 
  id_user: 5, 
  id_book: 22, 
  title: "El color que cayó del cielo", 
  author: "H.P. Lovecraft", 
  type: "Tapa Blanda", 
  price: 20.99, 
  image: "https://m.media-amazon.com/images/I/71yIBe3FaCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "160",
  year: "1927",
  rating: 4.2,
  sinopsis: "Un meteorito de color imposible transforma una granja rural en Massachusetts. La radiación alien contamina la tierra, los cultivos y los habitantes, llevándolos a una decadencia grotesca y sobrenatural."
},
{ 
  id_user: 5, 
  id_book: 23, 
  title: "El caso de Charles Dexter Ward", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546537819i/58115.jpg", 
  genre: "Terror",
  pages: "208",
  year: "1941",
  rating: 4.3,
  sinopsis: "Novela sobre Charles Ward, quien investiga a su ancestro Joseph Curwen, un hechicero colonial. Ward descubre secretos de alquimia y necromancia que lo llevan por un camino de horror y transformación."
},
{ 
  id_user: 5, 
  id_book: 24, 
  title: "El horror de Dunwich", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/81jQYca-OCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "176",
  year: "1929",
  rating: 4.1,
  sinopsis: "En el pueblo decadente de Dunwich, Wilbur Whateley crece de manera anormal. Su muerte desata una criatura invisible que aterroriza la región, revelando conexiones con entidades cósmicas ancestrales."
},
{ 
  id_user: 5, 
  id_book: 25, 
  title: "La sombra sobre Innsmouth", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/383/original/portada_la-sombra-sobre-innsmouth_h-p-lovecraft_202310311551.jpg", 
  genre: "Terror",
  pages: "144",
  year: "1931",
  rating: 4.5,
  sinopsis: "Un investigador visita el misterioso pueblo costero de Innsmouth y descubre que sus habitantes han hecho un pacto con criaturas marinas. Una historia de transformación y horror hereditario."
},
{ 
  id_user: 1, 
  id_book: 26, 
  title: "Los pilares de la Tierra", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91FU2wSBo5L._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "1008",
  year: "1989",
  rating: 4.7,
  sinopsis: "Épica novela ambientada en el siglo XII sobre la construcción de una catedral gótica en el ficticio Kingsbridge. Entrelaza las vidas de nobles, clérigos y constructores en una Inglaterra medieval llena de intrigas y pasiones."
},
{ 
  id_user: 2, 
  id_book: 27, 
  title: "La caída de los gigantes", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://imagessl5.casadellibro.com/a/l/s5/35/9788401337635.webp", 
  genre: "Novela Histórica",
  pages: "864",
  year: "2010",
  rating: 4.5,
  sinopsis: "Primera novela de la trilogía del Siglo XX. Sigue a cinco familias de diferentes países durante la Primera Guerra Mundial, mostrando cómo los grandes eventos históricos afectan las vidas ordinarias."
},
{ 
  id_user: 3, 
  id_book: 28, 
  title: "El invierno del mundo", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://m.media-amazon.com/images/I/81xCjUmfUmL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "940",
  year: "2012",
  rating: 4.4,
  sinopsis: "Segunda parte de la trilogía del Siglo XX. Las mismas familias enfrentan la Segunda Guerra Mundial, desde la Guerra Civil Española hasta Pearl Harbor, mostrando la lucha contra el fascismo."
},
{ 
  id_user: 4, 
  id_book: 29, 
  title: "El umbral de la eternidad", 
  author: "Ken Follett", 
  type: "Tapa Blanda", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/91JbZJ+w0aS._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "1152",
  year: "2014",
  rating: 4.3,
  sinopsis: "Conclusión de la trilogía del Siglo XX. Desde la construcción del Muro de Berlín hasta su caída, siguiendo a las familias durante la Guerra Fría, los derechos civiles y los cambios sociales."
},
{ 
  id_user: 5, 
  id_book: 30, 
  title: "La armadura de la luz", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/817ylM6zHsL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "912",
  year: "2023",
  rating: 4.2,
  sinopsis: "Precuela de Los Pilares de la Tierra. Ambientada en la Inglaterra del siglo X, narra la construcción del primer asentamiento en Kingsbridge durante las invasiones vikingas y los conflictos sajones."
},
{ 
  id_user: 1, 
  id_book: 31, 
  title: "La Tormenta", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_la-rueda-del-tiempo-n-1214-la-tormenta_robert-jordan_202105261615.jpg", 
  genre: "Fantasía",
  pages: "1216",
  year: "2013",
  rating: 4.8,
  sinopsis: "Cuarta novela de El Archivo de las Tormentas. Kaladin lucha con sus demonios internos mientras Shallan explora su identidad múltiple. Las fuerzas de Odium se preparan para la Desolación definitiva en Roshar."
},
{ 
  id_user: 2, 
  id_book: 32, 
  title: "Torres de Medianoche", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91rd0eczVEL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "864",
  year: "2010",
  rating: 4.6,
  sinopsis: "Decimotercera novela de La Rueda del Tiempo, completada por Sanderson. Mat se casa con Tuon, Perrin rescata a Faile del pasado, y Rand se prepara para la Última Batalla contra el Oscuro."
},
{ 
  id_user: 3, 
  id_book: 33, 
  title: "Un recuerdo de Luz", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/91TyzsluhoL.jpg", 
  genre: "Fantasía",
  pages: "896",
  year: "2014",
  rating: 4.7,
  sinopsis: "Último libro de La Rueda del Tiempo. La Última Batalla se libra en múltiples frentes mientras Rand enfrenta al Oscuro en una confrontación que determinará el destino del mundo."
},
{ 
  id_user: 4, 
  id_book: 34, 
  title: "El Ojo del Mundo", 
  author: "Robert Jordan", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_el-ojo-del-mundo-n-0114_robert-jordan_201910151031.jpg", 
  genre: "Fantasía",
  pages: "832",
  year: "1990",
  rating: 4.4,
  sinopsis: "Primera novela de La Rueda del Tiempo. Rand al'Thor abandona su aldea cuando trollocs la atacan. Descubre que es el Dragón Renacido, destinado a enfrentar al Oscuro en la Última Batalla."
},
{ 
  id_user: 5, 
  id_book: 35, 
  title: "La Gran Cacería", 
  author: "Robert Jordan", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_la-gran-caceria-n-0214_robert-jordan_201910151032.jpg", 
  genre: "Fantasía",
  pages: "704",
  year: "1990",
  rating: 4.3,
  sinopsis: "Segunda novela de La Rueda del Tiempo. Rand y sus compañeros buscan el Cuerno de Valere mientras Padan Fain escapa con la daga de Shadar Logoth. Rand acepta gradualmente su destino."
},
{ 
  id_user: 1, 
  id_book: 36, 
  title: "Roma soy yo", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "768",
  year: "2018",
  rating: 4.6,
  sinopsis: "Tercera novela de la saga de Trajano. El emperador enfrenta las revueltas judías y planea la conquista de Mesopotamia, mientras los enemigos internos conspiran contra él en la cúspide de su poder."
},
{ 
  id_user: 2, 
  id_book: 37, 
  title: "Circo Máximo", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/94/original/circo-maximo_9788408117117.jpg", 
  genre: "Novela Histórica",
  pages: "656",
  year: "2013",
  rating: 4.5,
  sinopsis: "Segunda parte de la trilogía de Trajano. El emperador consolida su poder mientras enfrenta las guerras dacias. Una épica que mezcla batallas, política romana y la construcción del Imperio en su apogeo."
},
{ 
  id_user: 3, 
  id_book: 38, 
  title: "Y Julia retó a los dioses", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/311/original/portada_y-julia-reto-a-los-dioses_santiago-posteguillo_202001150940.jpg", 
  genre: "Novela Histórica",
  pages: "896",
  year: "2020",
  rating: 4.7,
  sinopsis: "Novela sobre Julia Domna, esposa del emperador Septimio Severo. Una mujer siria que desafió las tradiciones romanas y se convirtió en una de las figuras más influyentes del Imperio Romano."
},
{ 
  id_user: 4, 
  id_book: 39, 
  title: "Los asesinos del emperador", 
  author: "Santiago Posteguillo", 
  type: "Tapa Blanda", 
  price: 24.99, 
  image: "https://www.santiagoposteguillo.es/wp-content/uploads/portada-asesinos.jpg", 
  genre: "Novela Histórica",
  pages: "592",
  year: "2011",
  rating: 4.4,
  sinopsis: "Primera novela de la saga de Trajano. Narra los primeros años del futuro emperador, desde su juventud en Hispania hasta su ascenso político, enfrentando conspiraciones y batallas."
},
{ 
  id_user: 5, 
  id_book: 40, 
  title: "Africanus", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/81NTQW75bIL._UF1000,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "672",
  year: "2006",
  rating: 4.8,
  sinopsis: "Primera novela de la trilogía de Escipión. Narra la juventud de Publio Cornelio Escipión, quien se convertirá en el conquistador de Cartago y uno de los generales más brillantes de Roma."
},
{ 
  id_user: 1, 
  id_book: 41, 
  title: "Harry Potter y el cáliz de fuego", 
  author: "J.K. Rowling", 
  type: "Tapa Blanda", 
  price: 34.99, 
  image: "https://m.media-amazon.com/images/I/91a2FifMS8L.jpg", 
  genre: "Fantasía",
  pages: "736",
  year: "2000",
  rating: 4.6,
  sinopsis: "Cuarta novela de Harry Potter. Harry participa en el peligroso Torneo de los Tres Magos y se enfrenta al regreso de Lord Voldemort. Un punto de inflexión hacia la madurez y el peligro real."
},
{ 
  id_user: 1, 
  id_book: 42, 
  title: "Reina Roja", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/71GC9IBeQjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Thriller",
  pages: "464",
  year: "2018",
  rating: 4.6,
  sinopsis: "Antonia Scott es especial. Muy especial. No es policía ni criminalista. Nunca ha empuñado un arma ni llevado una placa, y, sin embargo, ha resuelto decenas de crímenes. Pero hace un tiempo que Antonia no sale de su ático de Lavapiés."
},
{ 
  id_user: 1, 
  id_book: 43, 
  title: "Loba Negra", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Blanda", 
  price: 28.99, 
  image: "https://imagessl7.casadellibro.com/a/l/s5/97/9788466666497.webp", 
  genre: "Thriller",
  pages: "416",
  year: "2019",
  rating: 4.4,
  sinopsis: "Antonia Scott regresa en esta secuela de Reina Roja. Cuando la hija de la persona más rica de España es secuestrada, Antonia y Jon Gutiérrez deben enfrentarse a un enemigo que conoce todos sus secretos y debilidades."
},
{ 
  id_user: 1, 
  id_book: 44, 
  title: "Rey Blanco", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://imagessl5.casadellibro.com/a/l/s5/45/9788466668545.webp", 
  genre: "Thriller",
  pages: "448",
  year: "2020",
  rating: 4.5,
  sinopsis: "Tercera entrega de la trilogía. Antonia Scott se enfrenta a su mayor desafío cuando su mentor Mentor es secuestrado. Una carrera contrarreloj que la llevará a los límites de sus capacidades y pondrá a prueba todo lo que ha aprendido."
},
{ 
  id_user: 1, 
  id_book: 45, 
  title: "Cicatriz", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Blanda", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/718JlYPHi9L._AC_UF894,1000_QL80_.jpg", 
  genre: "Thriller",
  pages: "384",
  year: "2015",
  rating: 4.2,
  sinopsis: "Thriller independiente sobre Tom, un hombre corriente cuya vida cambia radicalmente cuando presencia un asesinato. Una historia sobre la supervivencia, la venganza y cómo las cicatrices del pasado pueden determinar nuestro futuro."
},
{ 
  id_user: 1, 
  id_book: 46, 
  title: "El Paciente", 
  author: "Juan Gómez-Jurado", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/61E4a1a-HlL._AC_UF894,1000_QL80_.jpg", 
  genre: "Thriller",
  pages: "352",
  year: "2014",
  rating: 4.3,
  sinopsis: "Un psiquiatra recibe a un paciente que afirma ser Dios. Lo que comienza como una sesión rutinaria se convierte en un inquietante juego psicológico donde la realidad y la locura se entremezclan de forma perturbadora."
},
{ 
  id_user: 1, 
  id_book: 47, 
  title: "El Hobbit", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://m.media-amazon.com/images/I/81aYpbH9opS._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "368",
  year: "1937",
  rating: 4.7,
  sinopsis: "Bilbo Bolsón es un hobbit acomodado y sedentario hasta que el mago Gandalf y un grupo de enanos lo arrastran a una aventura para recuperar el tesoro custodiado por el dragón Smaug en la Montaña Solitaria. Un viaje que cambiará su vida para siempre."
},
{ 
  id_user: 1, 
  id_book: 48, 
  title: "La Comunidad del Anillo", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://quelibroleo.com/images/libros/libro_1322009582.jpg", 
  genre: "Fantasía",
  pages: "576",
  year: "1954",
  rating: 4.8,
  sinopsis: "Primera parte de El Señor de los Anillos. Frodo Bolsón hereda un anillo mágico que resulta ser el Anillo Único del Señor Oscuro Sauron. Junto con la Comunidad del Anillo, emprende un peligroso viaje para destruirlo en Mount Doom."
},
{ 
  id_user: 1, 
  id_book: 49, 
  title: "Las Dos Torres", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/91sKjSJabqL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "544",
  year: "1954",
  rating: 4.7,
  sinopsis: "Segunda parte de la saga. La Comunidad se ha separado. Frodo y Sam continúan hacia Mordor con la traicionera ayuda de Gollum, mientras Aragorn, Legolas y Gimli persiguen a los orcos que capturaron a Merry y Pippin."
},
{ 
  id_user: 1, 
  id_book: 50, 
  title: "El Retorno del Rey", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91SI8FEoMuL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "624",
  year: "1955",
  rating: 4.9,
  sinopsis: "Conclusión épica de El Señor de los Anillos. Aragorn reclama su trono como Rey de Gondor, mientras Frodo y Sam enfrentan los peligros finales para destruir el Anillo en las llamas del Monte Doom y derrotar definitivamente a Sauron."
},
  // data.ts - Actualización de libros 51-80 con campos completos
// filepath: c:\Users\jta_j\OneDrive\Documentos\Cursos\CodeNocht\03_Repositorios Git\modulo7\modulo7\retosEvaluables\reactAppBook\src\config\data.ts

// Reemplazar los libros 51-80 con todos los campos:

{ 
  id_user: 1, 
  id_book: 51, 
  title: "El Silmarillion", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91j7JtU5SjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "480",
  year: "1977",
  rating: 4.3,
  sinopsis: "La historia completa de la Tierra Media desde su creación. Relata la música de los Ainur, el despertar de los Elfos, las guerras contra Morgoth, la forja de los Silmarils y los eventos que preceden a El Hobbit y El Señor de los Anillos."
},
{ 
  id_user: 1, 
  id_book: 52, 
  title: "Un mago de Terramar", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://images.librotea.com/uploads/media/2024/02/29/historias-de-terramar-i.jpeg", 
  genre: "Fantasía",
  pages: "224",
  year: "1968",
  rating: 4.4,
  sinopsis: "Primera novela del Ciclo de Terramar. Ged, un joven mago impetuoso, libera accidentalmente una sombra maligna que lo persigue. Debe emprender un viaje de autodescubrimiento y madurez para enfrentar y comprender su propia oscuridad interior."
},
{ 
  id_user: 1, 
  id_book: 53, 
  title: "La mano izquierda de la oscuridad", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/320/original/portada_la-mano-izquierda-de-la-oscuridad_ursula-k-le-guin_202006041508.jpg", 
  genre: "Ciencia Ficción",
  pages: "304",
  year: "1969",
  rating: 4.2,
  sinopsis: "Obra maestra de la ciencia ficción. En el planeta Gethen, un enviado humano debe navegar entre la política y la cultura de una sociedad ambisexual. Una exploración profunda sobre género, política y la naturaleza humana."
},
{ 
  id_user: 1, 
  id_book: 54, 
  title: "Los desposeídos", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91awx73viIL.jpg", 
  genre: "Ciencia Ficción",
  pages: "384",
  year: "1974",
  rating: 4.5,
  sinopsis: "Shevek, un físico brillante del planeta anarquista Anarres, viaja al mundo capitalista Urras en busca de unificar las teorías físicas. Una poderosa reflexión sobre utopía, política, y la búsqueda del conocimiento científico."
},
{ 
  id_user: 1, 
  id_book: 55, 
  title: "Las tumbas de Atuan", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://m.media-amazon.com/images/I/81feP85w6sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "192",
  year: "1971",
  rating: 4.3,
  sinopsis: "Segunda novela de Terramar. Tenar, la suma sacerdotisa de las Tumbas de Atuan, encuentra su mundo trastornado cuando el mago Ged llega buscando la mitad perdida del Anillo de Erreth-Akbe. Una historia sobre liberación y autodeterminación."
},
{ 
  id_user: 1, 
  id_book: 56, 
  title: "La costa más lejana", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/81LOSKQX-sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "272",
  year: "1972",
  rating: 4.4,
  sinopsis: "Tercera novela de Terramar. El príncipe Arren acompaña a Ged en una misión para descubrir por qué la magia está desapareciendo del mundo. Un viaje hacia las tierras más lejanas donde enfrentarán la fuente de un mal ancestral."
},
{ 
  id_user: 1, 
  id_book: 57, 
  title: "La llamada de Cthulhu", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/292/original/portada_la-llamada-de-cthulhu_h-p-lovecraft_201904111457.jpg", 
  genre: "Terror",
  pages: "192",
  year: "1928",
  rating: 4.4,
  sinopsis: "Relato icónico del horror cósmico. Un investigador descubre cultos secretos que adoran a Cthulhu, una entidad cósmica ancestral que yace dormida en la ciudad sumergida de R'lyeh, esperando despertar para dominar la humanidad."
},
{ 
  id_user: 1, 
  id_book: 58, 
  title: "El color que cayó del cielo", 
  author: "H.P. Lovecraft", 
  type: "Tapa Blanda", 
  price: 20.99, 
  image: "https://m.media-amazon.com/images/I/71yIBe3FaCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "160",
  year: "1927",
  rating: 4.2,
  sinopsis: "Un meteorito de color imposible transforma una granja rural en Massachusetts. La radiación alien contamina la tierra, los cultivos y los habitantes, llevándolos a una decadencia grotesca y sobrenatural."
},
{ 
  id_user: 1, 
  id_book: 59, 
  title: "El caso de Charles Dexter Ward", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546537819i/58115.jpg", 
  genre: "Terror",
  pages: "208",
  year: "1941",
  rating: 4.3,
  sinopsis: "Novela sobre Charles Ward, quien investiga a su ancestro Joseph Curwen, un hechicero colonial. Ward descubre secretos de alquimia y necromancia que lo llevan por un camino de horror y transformación."
},
{ 
  id_user: 1, 
  id_book: 60, 
  title: "El horror de Dunwich", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/81jQYca-OCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "176",
  year: "1929",
  rating: 4.1,
  sinopsis: "En el pueblo decadente de Dunwich, Wilbur Whateley crece de manera anormal. Su muerte desata una criatura invisible que aterroriza la región, revelando conexiones con entidades cósmicas ancestrales."
},
{ 
  id_user: 1, 
  id_book: 61, 
  title: "La sombra sobre Innsmouth", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/383/original/portada_la-sombra-sobre-innsmouth_h-p-lovecraft_202310311551.jpg", 
  genre: "Terror",
  pages: "144",
  year: "1931",
  rating: 4.5,
  sinopsis: "Un investigador visita el misterioso pueblo costero de Innsmouth y descubre que sus habitantes han hecho un pacto con criaturas marinas. Una historia de transformación y horror hereditario."
},
{ 
  id_user: 1, 
  id_book: 62, 
  title: "La caída de los gigantes", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://imagessl5.casadellibro.com/a/l/s5/35/9788401337635.webp", 
  genre: "Novela Histórica",
  pages: "864",
  year: "2010",
  rating: 4.5,
  sinopsis: "Primera novela de la trilogía del Siglo XX. Sigue a cinco familias de diferentes países durante la Primera Guerra Mundial, mostrando cómo los grandes eventos históricos afectan las vidas ordinarias."
},
{ 
  id_user: 1, 
  id_book: 63, 
  title: "El invierno del mundo", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://m.media-amazon.com/images/I/81xCjUmfUmL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "940",
  year: "2012",
  rating: 4.4,
  sinopsis: "Segunda parte de la trilogía del Siglo XX. Las mismas familias enfrentan la Segunda Guerra Mundial, desde la Guerra Civil Española hasta Pearl Harbor, mostrando la lucha contra el fascismo."
},
{ 
  id_user: 1, 
  id_book: 64, 
  title: "El umbral de la eternidad", 
  author: "Ken Follett", 
  type: "Tapa Blanda", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/91JbZJ+w0aS._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "1152",
  year: "2014",
  rating: 4.3,
  sinopsis: "Conclusión de la trilogía del Siglo XX. Desde la construcción del Muro de Berlín hasta su caída, siguiendo a las familias durante la Guerra Fría, los derechos civiles y los cambios sociales."
},
{ 
  id_user: 1, 
  id_book: 65, 
  title: "La armadura de la luz", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/817ylM6zHsL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "912",
  year: "2023",
  rating: 4.2,
  sinopsis: "Precuela de Los Pilares de la Tierra. Ambientada en la Inglaterra del siglo X, narra la construcción del primer asentamiento en Kingsbridge durante las invasiones vikingas y los conflictos sajones."
},
{ 
  id_user: 1, 
  id_book: 66, 
  title: "Torres de Medianoche", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91rd0eczVEL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "864",
  year: "2010",
  rating: 4.6,
  sinopsis: "Decimotercera novela de La Rueda del Tiempo, completada por Sanderson. Mat se casa con Tuon, Perrin rescata a Faile del pasado, y Rand se prepara para la Última Batalla contra el Oscuro."
},
{ 
  id_user: 1, 
  id_book: 67, 
  title: "Un recuerdo de Luz", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/91TyzsluhoL.jpg", 
  genre: "Fantasía",
  pages: "896",
  year: "2014",
  rating: 4.7,
  sinopsis: "Último libro de La Rueda del Tiempo. La Última Batalla se libra en múltiples frentes mientras Rand enfrenta al Oscuro en una confrontación que determinará el destino del mundo."
},
{ 
  id_user: 1, 
  id_book: 68, 
  title: "El Ojo del Mundo", 
  author: "Robert Jordan", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_el-ojo-del-mundo-n-0114_robert-jordan_201910151031.jpg", 
  genre: "Fantasía",
  pages: "832",
  year: "1990",
  rating: 4.4,
  sinopsis: "Primera novela de La Rueda del Tiempo. Rand al'Thor abandona su aldea cuando trollocs la atacan. Descubre que es el Dragón Renacido, destinado a enfrentar al Oscuro en la Última Batalla."
},
{ 
  id_user: 1, 
  id_book: 69, 
  title: "La Gran Cacería", 
  author: "Robert Jordan", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_la-gran-caceria-n-0214_robert-jordan_201910151032.jpg", 
  genre: "Fantasía",
  pages: "704",
  year: "1990",
  rating: 4.3,
  sinopsis: "Segunda novela de La Rueda del Tiempo. Rand y sus compañeros buscan el Cuerno de Valere mientras Padan Fain escapa con la daga de Shadar Logoth. Rand acepta gradualmente su destino."
},
{ 
  id_user: 1, 
  id_book: 70, 
  title: "Roma soy yo", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "768",
  year: "2018",
  rating: 4.6,
  sinopsis: "Tercera novela de la saga de Trajano. El emperador enfrenta las revueltas judías y planea la conquista de Mesopotamia, mientras los enemigos internos conspiran contra él en la cúspide de su poder."
},
{ 
  id_user: 1, 
  id_book: 71, 
  title: "Circo Máximo", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/94/original/circo-maximo_9788408117117.jpg", 
  genre: "Novela Histórica",
  pages: "656",
  year: "2013",
  rating: 4.5,
  sinopsis: "Segunda parte de la trilogía de Trajano. El emperador consolida su poder mientras enfrenta las guerras dacias. Una épica que mezcla batallas, política romana y la construcción del Imperio en su apogeo."
},
{ 
  id_user: 1, 
  id_book: 72, 
  title: "Y Julia retó a los dioses", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/311/original/portada_y-julia-reto-a-los-dioses_santiago-posteguillo_202001150940.jpg", 
  genre: "Novela Histórica",
  pages: "896",
  year: "2020",
  rating: 4.7,
  sinopsis: "Novela sobre Julia Domna, esposa del emperador Septimio Severo. Una mujer siria que desafió las tradiciones romanas y se convirtió en una de las figuras más influyentes del Imperio Romano."
},
{ 
  id_user: 1, 
  id_book: 73, 
  title: "Los asesinos del emperador", 
  author: "Santiago Posteguillo", 
  type: "Tapa Blanda", 
  price: 24.99, 
  image: "https://www.santiagoposteguillo.es/wp-content/uploads/portada-asesinos.jpg", 
  genre: "Novela Histórica",
  pages: "592",
  year: "2011",
  rating: 4.4,
  sinopsis: "Primera novela de la saga de Trajano. Narra los primeros años del futuro emperador, desde su juventud en Hispania hasta su ascenso político, enfrentando conspiraciones y batallas."
},
{ 
  id_user: 1, 
  id_book: 74, 
  title: "Africanus", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/81NTQW75bIL._UF1000,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "672",
  year: "2006",
  rating: 4.8,
  sinopsis: "Primera novela de la trilogía de Escipión. Narra la juventud de Publio Cornelio Escipión, quien se convertirá en el conquistador de Cartago y uno de los generales más brillantes de Roma."
},
{ 
  id_user: 2, 
  id_book: 75, 
  title: "Fundación", 
  author: "Isaac Asimov", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://www.baobablibros.es/imagenes_grandes/9788497/978849759924.GIF", 
  genre: "Ciencia Ficción",
  pages: "320",
  year: "1951",
  rating: 4.5,
  sinopsis: "Primera novela de la saga Fundación. En un futuro lejano, el matemático Hari Seldon prevé la caída del Imperio Galáctico y desarrolla la psicohistoria para minimizar el período de barbarie que seguirá, estableciendo una Fundación en los confines de la galaxia."
},
{ 
  id_user: 2, 
  id_book: 76, 
  title: "Yo, Robot", 
  author: "Isaac Asimov", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://m.media-amazon.com/images/I/71DquplUL-L._AC_UF894,1000_QL80_.jpg", 
  genre: "Ciencia Ficción",
  pages: "256",
  year: "1950",
  rating: 4.3,
  sinopsis: "Colección de relatos sobre robots positrónicos y las tres leyes de la robótica. Susan Calvin, robopsicóloga, narra la evolución de los robots desde simples máquinas hasta seres casi conscientes, explorando las implicaciones éticas y filosóficas de la inteligencia artificial."
},
{ 
  id_user: 2, 
  id_book: 77, 
  title: "Los propios dioses", 
  author: "Isaac Asimov", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://m.media-amazon.com/images/I/71GGALG6zjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Ciencia Ficción",
  pages: "288",
  year: "1972",
  rating: 4.2,
  sinopsis: "Ganadora del premio Hugo y Nebula. La humanidad descubre una fuente de energía ilimitada mediante el intercambio de materia con un universo paralelo, pero un científico descubre que este proceso puede destruir ambos universos."
},
{ 
  id_user: 2, 
  id_book: 78, 
  title: "Las bóvedas de acero", 
  author: "Isaac Asimov", 
  type: "Tapa Blanda", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/71sEetDkeIL.jpg", 
  genre: "Ciencia Ficción",
  pages: "244",
  year: "1954",
  rating: 4.1,
  sinopsis: "Primera novela de la saga de robots protagonizada por Elijah Baley y R. Daneel. En un futuro donde los humanos viven en ciudades cubiertas y temen al aire libre, un detective debe resolver un asesinato con la ayuda de un robot humanoide, desafiando sus prejuicios."
},
{ 
  id_user: 2, 
  id_book: 79, 
  title: "El sol desnudo", 
  author: "Isaac Asimov", 
  type: "Tapa Dura", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/613SX2R1wJL.jpg", 
  genre: "Ciencia Ficción",
  pages: "272",
  year: "1957",
  rating: 4.0,
  sinopsis: "Segunda novela de Elijah Baley y R. Daneel. El detective terrestre viaja al planeta Aurora para resolver un asesinato en una sociedad donde los humanos evitan el contacto físico y viven aislados, dependiendo completamente de los robots."
},
{ 
  id_user: 2, 
  id_book: 80, 
  title: "Los pilares de la Tierra", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91FU2wSBo5L._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "1008",
  year: "1989",
  rating: 4.7,
  sinopsis: "Épica novela ambientada en el siglo XII sobre la construcción de una catedral gótica en el ficticio Kingsbridge. Entrelaza las vidas de nobles, clérigos y constructores en una Inglaterra medieval llena de intrigas y pasiones."
},
  // data.ts - Actualización de libros 81-100 con campos completos
// filepath: c:\Users\jta_j\OneDrive\Documentos\Cursos\CodeNocht\03_Repositorios Git\modulo7\modulo7\retosEvaluables\reactAppBook\src\config\data.ts

// Reemplazar los libros 81-100 con todos los campos:

{ 
  id_user: 2, 
  id_book: 81, 
  title: "Harry Potter y el cáliz de fuego", 
  author: "J.K. Rowling", 
  type: "Tapa Blanda", 
  price: 34.99, 
  image: "https://m.media-amazon.com/images/I/91a2FifMS8L.jpg", 
  genre: "Fantasía",
  pages: "736",
  year: "2000",
  rating: 4.6,
  sinopsis: "Cuarta novela de Harry Potter. Harry participa en el peligroso Torneo de los Tres Magos y se enfrenta al regreso de Lord Voldemort. Un punto de inflexión hacia la madurez y el peligro real."
},
{ 
  id_user: 2, 
  id_book: 82, 
  title: "El Hobbit", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://m.media-amazon.com/images/I/81aYpbH9opS._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "368",
  year: "1937",
  rating: 4.7,
  sinopsis: "Bilbo Bolsón es un hobbit acomodado y sedentario hasta que el mago Gandalf y un grupo de enanos lo arrastran a una aventura para recuperar el tesoro custodiado por el dragón Smaug en la Montaña Solitaria. Un viaje que cambiará su vida para siempre."
},
{ 
  id_user: 2, 
  id_book: 83, 
  title: "La Comunidad del Anillo", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://quelibroleo.com/images/libros/libro_1322009582.jpg", 
  genre: "Fantasía",
  pages: "576",
  year: "1954",
  rating: 4.8,
  sinopsis: "Primera parte de El Señor de los Anillos. Frodo Bolsón hereda un anillo mágico que resulta ser el Anillo Único del Señor Oscuro Sauron. Junto con la Comunidad del Anillo, emprende un peligroso viaje para destruirlo en Mount Doom."
},
{ 
  id_user: 2, 
  id_book: 84, 
  title: "Las Dos Torres", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/91sKjSJabqL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "544",
  year: "1954",
  rating: 4.7,
  sinopsis: "Segunda parte de la saga. La Comunidad se ha separado. Frodo y Sam continúan hacia Mordor con la traicionera ayuda de Gollum, mientras Aragorn, Legolas y Gimli persiguen a los orcos que capturaron a Merry y Pippin."
},
{ 
  id_user: 2, 
  id_book: 85, 
  title: "El Retorno del Rey", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91SI8FEoMuL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "624",
  year: "1955",
  rating: 4.9,
  sinopsis: "Conclusión épica de El Señor de los Anillos. Aragorn reclama su trono como Rey de Gondor, mientras Frodo y Sam enfrentan los peligros finales para destruir el Anillo en las llamas del Monte Doom y derrotar definitivamente a Sauron."
},
{ 
  id_user: 2, 
  id_book: 86, 
  title: "El Silmarillion", 
  author: "J.R.R. Tolkien", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://m.media-amazon.com/images/I/91j7JtU5SjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "480",
  year: "1977",
  rating: 4.3,
  sinopsis: "La historia completa de la Tierra Media desde su creación. Relata la música de los Ainur, el despertar de los Elfos, las guerras contra Morgoth, la forja de los Silmarils y los eventos que preceden a El Hobbit y El Señor de los Anillos."
},
{ 
  id_user: 2, 
  id_book: 87, 
  title: "Un mago de Terramar", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://images.librotea.com/uploads/media/2024/02/29/historias-de-terramar-i.jpeg", 
  genre: "Fantasía",
  pages: "224",
  year: "1968",
  rating: 4.4,
  sinopsis: "Primera novela del Ciclo de Terramar. Ged, un joven mago impetuoso, libera accidentalmente una sombra maligna que lo persigue. Debe emprender un viaje de autodescubrimiento y madurez para enfrentar y comprender su propia oscuridad interior."
},
{ 
  id_user: 2, 
  id_book: 88, 
  title: "La mano izquierda de la oscuridad", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/320/original/portada_la-mano-izquierda-de-la-oscuridad_ursula-k-le-guin_202006041508.jpg", 
  genre: "Ciencia Ficción",
  pages: "304",
  year: "1969",
  rating: 4.2,
  sinopsis: "Obra maestra de la ciencia ficción. En el planeta Gethen, un enviado humano debe navegar entre la política y la cultura de una sociedad ambisexual. Una exploración profunda sobre género, política y la naturaleza humana."
},
{ 
  id_user: 2, 
  id_book: 89, 
  title: "Los desposeídos", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://m.media-amazon.com/images/I/91awx73viIL.jpg", 
  genre: "Ciencia Ficción",
  pages: "384",
  year: "1974",
  rating: 4.5,
  sinopsis: "Shevek, un físico brillante del planeta anarquista Anarres, viaja al mundo capitalista Urras en busca de unificar las teorías físicas. Una poderosa reflexión sobre utopía, política, y la búsqueda del conocimiento científico."
},
{ 
  id_user: 2, 
  id_book: 90, 
  title: "Las tumbas de Atuan", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://m.media-amazon.com/images/I/81feP85w6sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "192",
  year: "1971",
  rating: 4.3,
  sinopsis: "Segunda novela de Terramar. Tenar, la suma sacerdotisa de las Tumbas de Atuan, encuentra su mundo trastornado cuando el mago Ged llega buscando la mitad perdida del Anillo de Erreth-Akbe. Una historia sobre liberación y autodeterminación."
},
{ 
  id_user: 2, 
  id_book: 91, 
  title: "La costa más lejana", 
  author: "Ursula K. Le Guin", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/81LOSKQX-sL._UF1000,1000_QL80_.jpg", 
  genre: "Fantasía",
  pages: "272",
  year: "1972",
  rating: 4.4,
  sinopsis: "Tercera novela de Terramar. El príncipe Arren acompaña a Ged en una misión para descubrir por qué la magia está desapareciendo del mundo. Un viaje hacia las tierras más lejanas donde enfrentarán la fuente de un mal ancestral."
},
{ 
  id_user: 2, 
  id_book: 92, 
  title: "La llamada de Cthulhu", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/292/original/portada_la-llamada-de-cthulhu_h-p-lovecraft_201904111457.jpg", 
  genre: "Terror",
  pages: "192",
  year: "1928",
  rating: 4.4,
  sinopsis: "Relato icónico del horror cósmico. Un investigador descubre cultos secretos que adoran a Cthulhu, una entidad cósmica ancestral que yace dormida en la ciudad sumergida de R'lyeh, esperando despertar para dominar la humanidad."
},
{ 
  id_user: 2, 
  id_book: 93, 
  title: "El color que cayó del cielo", 
  author: "H.P. Lovecraft", 
  type: "Tapa Blanda", 
  price: 20.99, 
  image: "https://m.media-amazon.com/images/I/71yIBe3FaCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "160",
  year: "1927",
  rating: 4.2,
  sinopsis: "Un meteorito de color imposible transforma una granja rural en Massachusetts. La radiación alien contamina la tierra, los cultivos y los habitantes, llevándolos a una decadencia grotesca y sobrenatural."
},
{ 
  id_user: 2, 
  id_book: 94, 
  title: "El caso de Charles Dexter Ward", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 26.99, 
  image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546537819i/58115.jpg", 
  genre: "Terror",
  pages: "208",
  year: "1941",
  rating: 4.3,
  sinopsis: "Novela sobre Charles Ward, quien investiga a su ancestro Joseph Curwen, un hechicero colonial. Ward descubre secretos de alquimia y necromancia que lo llevan por un camino de horror y transformación."
},
{ 
  id_user: 2, 
  id_book: 95, 
  title: "El horror de Dunwich", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/81jQYca-OCL._AC_UF894,1000_QL80_.jpg", 
  genre: "Terror",
  pages: "176",
  year: "1929",
  rating: 4.1,
  sinopsis: "En el pueblo decadente de Dunwich, Wilbur Whateley crece de manera anormal. Su muerte desata una criatura invisible que aterroriza la región, revelando conexiones con entidades cósmicas ancestrales."
},
{ 
  id_user: 2, 
  id_book: 96, 
  title: "La sombra sobre Innsmouth", 
  author: "H.P. Lovecraft", 
  type: "Tapa Dura", 
  price: 25.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/383/original/portada_la-sombra-sobre-innsmouth_h-p-lovecraft_202310311551.jpg", 
  genre: "Terror",
  pages: "144",
  year: "1931",
  rating: 4.5,
  sinopsis: "Un investigador visita el misterioso pueblo costero de Innsmouth y descubre que sus habitantes han hecho un pacto con criaturas marinas. Una historia de transformación y horror hereditario."
},
{ 
  id_user: 2, 
  id_book: 97, 
  title: "El invierno del mundo", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://m.media-amazon.com/images/I/81xCjUmfUmL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "940",
  year: "2012",
  rating: 4.4,
  sinopsis: "Segunda parte de la trilogía del Siglo XX. Las mismas familias enfrentan la Segunda Guerra Mundial, desde la Guerra Civil Española hasta Pearl Harbor, mostrando la lucha contra el fascismo."
},
{ 
  id_user: 2, 
  id_book: 98, 
  title: "El umbral de la eternidad", 
  author: "Ken Follett", 
  type: "Tapa Blanda", 
  price: 23.99, 
  image: "https://m.media-amazon.com/images/I/91JbZJ+w0aS._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "1152",
  year: "2014",
  rating: 4.3,
  sinopsis: "Conclusión de la trilogía del Siglo XX. Desde la construcción del Muro de Berlín hasta su caída, siguiendo a las familias durante la Guerra Fría, los derechos civiles y los cambios sociales."
},
{ 
  id_user: 2, 
  id_book: 99, 
  title: "La armadura de la luz", 
  author: "Ken Follett", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/817ylM6zHsL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "912",
  year: "2023",
  rating: 4.2,
  sinopsis: "Precuela de Los Pilares de la Tierra. Ambientada en la Inglaterra del siglo X, narra la construcción del primer asentamiento en Kingsbridge durante las invasiones vikingas y los conflictos sajones."
},
{ 
  id_user: 2, 
  id_book: 100, 
  title: "La Tormenta", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 27.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_la-rueda-del-tiempo-n-1214-la-tormenta_robert-jordan_202105261615.jpg", 
  genre: "Fantasía",
  pages: "1216",
  year: "2013",
  rating: 4.8,
  sinopsis: "Cuarta novela de El Archivo de las Tormentas. Kaladin lucha con sus demonios internos mientras Shallan explora su identidad múltiple. Las fuerzas de Odium se preparan para la Desolación definitiva en Roshar."
},
// data.ts - Completar libros 101-107 y añadir 108-110 con nuevos géneros
// filepath: c:\Users\jta_j\OneDrive\Documentos\Cursos\CodeNocht\03_Repositorios Git\modulo7\modulo7\retosEvaluables\reactAppBook\src\config\data.ts

// Reemplazar desde el libro 101 y añadir hasta el 110:

{ 
  id_user: 2, 
  id_book: 101, 
  title: "Un recuerdo de Luz", 
  author: "Brandon Sanderson", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/91TyzsluhoL.jpg", 
  genre: "Fantasía",
  pages: "896",
  year: "2014",
  rating: 4.7,
  sinopsis: "Último libro de La Rueda del Tiempo. La Última Batalla se libra en múltiples frentes mientras Rand enfrenta al Oscuro en una confrontación que determinará el destino del mundo."
},
{ 
  id_user: 2, 
  id_book: 102, 
  title: "El Ojo del Mundo", 
  author: "Robert Jordan", 
  type: "Tapa Blanda", 
  price: 22.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_el-ojo-del-mundo-n-0114_robert-jordan_201910151031.jpg", 
  genre: "Fantasía",
  pages: "832",
  year: "1990",
  rating: 4.4,
  sinopsis: "Primera novela de La Rueda del Tiempo. Rand al'Thor abandona su aldea cuando trollocs la atacan. Descubre que es el Dragón Renacido, destinado a enfrentar al Oscuro en la Última Batalla."
},
{ 
  id_user: 2, 
  id_book: 103, 
  title: "La Gran Cacería", 
  author: "Robert Jordan", 
  type: "Tapa Dura", 
  price: 28.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/300/original/portada_la-gran-caceria-n-0214_robert-jordan_201910151032.jpg", 
  genre: "Fantasía",
  pages: "704",
  year: "1990",
  rating: 4.3,
  sinopsis: "Segunda novela de La Rueda del Tiempo. Rand y sus compañeros buscan el Cuerno de Valere mientras Padan Fain escapa con la daga de Shadar Logoth. Rand acepta gradualmente su destino."
},
{ 
  id_user: 2, 
  id_book: 104, 
  title: "Roma soy yo", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 29.99, 
  image: "https://m.media-amazon.com/images/I/719yqLXOmyL._AC_UF894,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "768",
  year: "2018",
  rating: 4.6,
  sinopsis: "Tercera novela de la saga de Trajano. El emperador enfrenta las revueltas judías y planea la conquista de Mesopotamia, mientras los enemigos internos conspiran contra él en la cúspide de su poder."
},
{ 
  id_user: 2, 
  id_book: 105, 
  title: "Y Julia retó a los dioses", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 30.99, 
  image: "https://www.planetadelibros.com/usuaris/libros/fotos/311/original/portada_y-julia-reto-a-los-dioses_santiago-posteguillo_202001150940.jpg", 
  genre: "Novela Histórica",
  pages: "896",
  year: "2020",
  rating: 4.7,
  sinopsis: "Novela sobre Julia Domna, esposa del emperador Septimio Severo. Una mujer siria que desafió las tradiciones romanas y se convirtió en una de las figuras más influyentes del Imperio Romano."
},
{ 
  id_user: 2, 
  id_book: 106, 
  title: "Los asesinos del emperador", 
  author: "Santiago Posteguillo", 
  type: "Tapa Blanda", 
  price: 24.99, 
  image: "https://www.santiagoposteguillo.es/wp-content/uploads/portada-asesinos.jpg", 
  genre: "Novela Histórica",
  pages: "592",
  year: "2011",
  rating: 4.4,
  sinopsis: "Primera novela de la saga de Trajano. Narra los primeros años del futuro emperador, desde su juventud en Hispania hasta su ascenso político, enfrentando conspiraciones y batallas."
},
{ 
  id_user: 2, 
  id_book: 107, 
  title: "Africanus", 
  author: "Santiago Posteguillo", 
  type: "Tapa Dura", 
  price: 31.99, 
  image: "https://m.media-amazon.com/images/I/81NTQW75bIL._UF1000,1000_QL80_.jpg", 
  genre: "Novela Histórica",
  pages: "672",
  year: "2006",
  rating: 4.8,
  sinopsis: "Primera novela de la trilogía de Escipión. Narra la juventud de Publio Cornelio Escipión, quien se convertirá en el conquistador de Cartago y uno de los generales más brillantes de Roma."
},
{ 
  id_user: 3, 
  id_book: 108, 
  title: "Meditaciones", 
  author: "Marco Aurelio", 
  type: "Tapa Dura", 
  price: 18.99, 
  image: "https://m.media-amazon.com/images/I/71x9Mn9CEPL._AC_UF894,1000_QL80_.jpg", 
  genre: "Filosofía",
  pages: "240",
  year: "180",
  rating: 4.6,
  sinopsis: "Reflexiones personales del emperador romano Marco Aurelio sobre la virtud estoica, el deber y la naturaleza humana. Una guía atemporal para vivir con sabiduría, disciplina y serenidad ante las adversidades de la vida."
},
{ 
  id_user: 3, 
  id_book: 109, 
  title: "El nombre de la rosa", 
  author: "Umberto Eco", 
  type: "Tapa Blanda", 
  price: 26.99, 
  image: "https://m.media-amazon.com/images/I/91P1xW6zKgL._AC_UF894,1000_QL80_.jpg", 
  genre: "Misterio",
  pages: "608",
  year: "1980",
  rating: 4.3,
  sinopsis: "En una abadía medieval, el franciscano Guillermo de Baskerville investiga una serie de misteriosas muertes. Una novela que combina misterio detectivesco con profundas reflexiones sobre conocimiento, fe y poder en la Edad Media."
},
{ 
  id_user: 3, 
  id_book: 110, 
  title: "Crimen y castigo", 
  author: "Fiódor Dostoyevski", 
  type: "Tapa Dura", 
  price: 24.99, 
  image: "https://m.media-amazon.com/images/I/81rR3rj9VjL._AC_UF894,1000_QL80_.jpg", 
  genre: "Clásicos",
  pages: "704",
  year: "1866",
  rating: 4.8,
  sinopsis: "Raskolnikov, un estudiante empobrecido en San Petersburgo, comete un asesinato creyendo estar por encima de la moral común. Una exploración psicológica magistral sobre culpa, redención y la naturaleza del bien y del mal."
}
];

export {books};